// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef tuto04_h
#define tuto04_h
#include <FL/Fl.H>
void funcbuttonclick();
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
Fl_Double_Window* win1();
int main();
#endif
